### ISSUE TITLE
Python3 changes "official" repository

### ISSUE THREAD

**Issue by SteveClement** [cwarden/muttils#3]
Dear

I just made some changes so muttils runs under Python3.

Where should I push these changes to?
What is the official repository?

/cc @cwarden @blacktrash

**Comment by blacktrash** [comment]
With DVCS everything is official ;-) but the original Mercurial repo is here:
https://bitbucket.org/blacktrash/muttils

**Comment by SteveClement** [comment]
Ok, thanks, I will clone and PR from here then.
I will make a separate branch for testing as I noticed a few issues and I have not tested all the other tools either.

**Comment by SteveClement** [comment]
Sorry to re-open this, but the Mercurial repo and the github one are out of sync.
@blacktrash

**Comment by blacktrash** [comment]
@SteveClement - I am not in charge of the Git repo here. I only maintain the Mercurial repo which is published on [Bitbucket](https://bitbucket.org/blacktrash/muttils) and also on [my server](https://blacktrash.org/hg/muttils/).
So far I have no intention to switch or duplicate, nevermind maintain this in Git. I can offer to apply patches if you don't want to collaborate via Bitbucket and am open to other proposals. Please understand though that at the moment I can't spend much time on muttils, sorry.

**Comment by cwarden** [comment]
I've brought this repo back in sync with http://www.blacktrash.org/hg/muttils/

**Comment by SteveClement** [comment]
@cwarden thanks for that....

**Comment by phloxic** [comment]
@cwarden, @SteveClement the hg repo has moved here: https://hg.phloxic.productions/muttils/
The latest version is a switch to python3: https://hg.phloxic.productions/muttils/rev/7ebc39518d18
Could be a bit quick an dirty, but I am running it atm.
Still needs hg for setup, but that shouldn't be too difficult to adapt.
